import { StatusProvider } from "@/types/status";

export const PROVIDERS: StatusProvider[] = [
  {
    id: 'bfl',
    name: 'Black Forest Labs',
    url: 'https://status.bfl.ml/history.rss',
    homePageUrl: 'https://status.bfl.ml',
  },
  {
    id: 'fal',
    name: 'Fal.ai',
    url: 'https://status.fal.ai/history.rss',
    homePageUrl: 'https://status.fal.ai',
  },
  {
    id: 'gcp-veo',
    name: 'Vertex AI Veo',
    url: 'https://status.cloud.google.com/en/feed.atom',
    homePageUrl: 'https://status.cloud.google.com/',
    keywords: ['Veo'],
  },
  {
    id: 'gcp-gemini',
    name: 'Vertex AI Gemini',
    url: 'https://status.cloud.google.com/en/feed.atom',
    homePageUrl: 'https://status.cloud.google.com/',
    keywords: ['Gemini', 'Vertex AI'],
  },
  {
    id: 'gcp-imagen',
    name: 'Vertex AI Imagen',
    url: 'https://status.cloud.google.com/en/feed.atom',
    homePageUrl: 'https://status.cloud.google.com/',
    keywords: ['Imagen'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    url: 'https://status.openai.com/feed.rss',
    homePageUrl: 'https://status.openai.com/',
  },
  {
    id: 'kling',
    name: 'Kling',
    url: 'https://modelstatus.ai',
    type: 'modelstatus_api',
    apiProviderId: 'kling',
    homePageUrl: 'https://www.modelstatus.ai/',
  },
  {
    id: 'minimax',
    name: 'Minimax',
    url: 'https://modelstatus.ai',
    type: 'modelstatus_api',
    apiProviderId: 'minimax',
    homePageUrl: 'https://www.modelstatus.ai/',
  },
  {
    id: 'bytedance',
    name: 'ByteDance',
    url: 'https://modelstatus.ai',
    type: 'modelstatus_api',
    apiProviderId: 'bytedance',
    homePageUrl: 'https://www.modelstatus.ai/',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    url: 'https://www.cloudflarestatus.com/api/v2/incidents/unresolved.json',
    type: 'cloudflare_api',
    homePageUrl: 'https://www.cloudflarestatus.com/',
  },
  {
    id: 'hasura',
    name: 'Hasura',
    url: 'https://hasura-status.com/feed.rss',
    homePageUrl: 'https://hasura-status.com/',
  },
];
